
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nick&Tori
 */
public class ECS extends javax.swing.JFrame {

    /**
     * Creates new form ECS
     */
    public ECS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        paneLogin = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        tabDashboard = new javax.swing.JTabbedPane();
        panEquipment = new javax.swing.JPanel();
        btnCheckOut = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lpaneEquipment = new javax.swing.JLayeredPane();
        paneCheckOut = new javax.swing.JPanel();
        scrollPane3 = new java.awt.ScrollPane();
        paneEdit = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfEquipmentId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfBuilding = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfName1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnCheckout2 = new javax.swing.JButton();
        paneCheckIn = new javax.swing.JPanel();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnStolen = new javax.swing.JButton();
        btnBroken = new javax.swing.JButton();
        btnLost = new javax.swing.JButton();
        paneEdit = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfEquipmentId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfBuilding = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfName1 = new javax.swing.JTextField();
        panReports = new javax.swing.JPanel();
        btnUserContingency = new javax.swing.JButton();
        btnBuildingInventory = new javax.swing.JButton();
        lpaneReports = new javax.swing.JLayeredPane();
        paneContingency = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        scrollPane4 = new java.awt.ScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        paneUserContingencies = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        scrollPane5 = new java.awt.ScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        paneBuildingInventory = new javax.swing.JPanel();
        btnContingency = new javax.swing.JButton();
        panProfile = new javax.swing.JPanel();
        panUsers = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        paneLogin.setBackground(new java.awt.Color(255, 255, 102));

        jButton9.setText("LOG IN");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneLoginLayout = new javax.swing.GroupLayout(paneLogin);
        paneLogin.setLayout(paneLoginLayout);
        paneLoginLayout.setHorizontalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLoginLayout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        paneLoginLayout.setVerticalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLoginLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(214, 214, 214))
        );

        jLayeredPane1.add(paneLogin, "card3");

        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnEdit.setLabel("Edit Inventory");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lpaneEquipment.setLayout(new java.awt.CardLayout());

        paneCheckOut.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paneEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        scrollPane1.add(jScrollPane2);

        jButton1.setText("Delete");

        jLabel1.setText("Name");

        jLabel4.setText("Price");

        jLabel5.setText("Building");

        jLabel6.setText("Date Added");

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel7.setText("EDIT INVENTORY");

        jLabel10.setText("Equipment Id");

        javax.swing.GroupLayout paneEditLayout = new javax.swing.GroupLayout(paneEdit);
        paneEdit.setLayout(paneEditLayout);
        paneEditLayout.setHorizontalGroup(
            paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditLayout.createSequentialGroup()
                .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(22, 22, 22)
                .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneEditLayout.setVerticalGroup(
            paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditLayout.createSequentialGroup()
                .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneEditLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnAdd)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        lpaneEquipment.add(paneEdit, "card4");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        scrollPane3.add(jScrollPane3);

        jLabel3.setText("CHECK OUT - EQUIPMENT");

        btnCheckout2.setText("Check Out");
        btnCheckout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckout2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCheckOutLayout = new javax.swing.GroupLayout(paneCheckOut);
        paneCheckOut.setLayout(paneCheckOutLayout);
        paneCheckOutLayout.setHorizontalGroup(
            paneCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckOutLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(paneCheckOutLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(paneCheckOutLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(btnCheckout2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneCheckOutLayout.setVerticalGroup(
            paneCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckOutLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnCheckout2)
                .addGap(50, 50, 50))
        );

        lpaneEquipment.add(paneCheckOut, "card3");

        paneCheckIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        scrollPane2.add(jScrollPane1);

        jLabel2.setText("CHECK IN - USER HISTORY");

        jButton2.setText("Check In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnStolen.setText("stolen");
        btnStolen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStolenActionPerformed(evt);
            }
        });

        btnBroken.setText("Broken");
        btnBroken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrokenActionPerformed(evt);
            }
        });

        btnLost.setText("Lost");
        btnLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCheckInLayout = new javax.swing.GroupLayout(paneCheckIn);
        paneCheckIn.setLayout(paneCheckInLayout);
        paneCheckInLayout.setHorizontalGroup(
            paneCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckInLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(paneCheckInLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBroken, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStolen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLost, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneCheckInLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneCheckInLayout.setVerticalGroup(
            paneCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckInLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(paneCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnStolen)
                    .addComponent(btnBroken)
                    .addComponent(btnLost))
                .addGap(56, 56, 56))
        );

        lpaneEquipment.add(paneCheckIn, "card3");

        paneEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        scrollPane1.add(jScrollPane2);

        jButton1.setText("Delete");

        jLabel1.setText("Name");

        jLabel4.setText("Price");

        jLabel5.setText("Building");

        jLabel6.setText("Date Added");

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel7.setText("EDIT INVENTORY");

        jLabel10.setText("Equipment Id");

        javax.swing.GroupLayout paneEditLayout = new javax.swing.GroupLayout(paneEdit);
        paneEdit.setLayout(paneEditLayout);
        paneEditLayout.setHorizontalGroup(
            paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditLayout.createSequentialGroup()
                .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(22, 22, 22)
                .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneEditLayout.setVerticalGroup(
            paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditLayout.createSequentialGroup()
                .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEquipmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(paneEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneEditLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addGroup(paneEditLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnAdd)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        lpaneEquipment.add(paneEdit, "card4");

        javax.swing.GroupLayout panEquipmentLayout = new javax.swing.GroupLayout(panEquipment);
        panEquipment.setLayout(panEquipmentLayout);
        panEquipmentLayout.setHorizontalGroup(
            panEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEquipmentLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lpaneEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panEquipmentLayout.setVerticalGroup(
            panEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEquipmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpaneEquipment)
                .addContainerGap())
            .addGroup(panEquipmentLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnCheckOut)
                .addGap(32, 32, 32)
                .addComponent(btnCheckIn)
                .addGap(33, 33, 33)
                .addComponent(btnEdit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabDashboard.addTab("Equipment", panEquipment);

        btnUserContingency.setText("User Contingency");
        btnUserContingency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserContingencyActionPerformed(evt);
            }
        });

        btnBuildingInventory.setText("Building Inventory");

        lpaneReports.setLayout(new java.awt.CardLayout());

        jTextField5.setText("jTextField5");

        jLabel8.setText("Total Financial Loss To Date:");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        scrollPane4.add(jScrollPane7);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        scrollPane4.add(jScrollPane6);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        scrollPane4.add(jScrollPane5);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        scrollPane4.add(jScrollPane4);

        javax.swing.GroupLayout paneContingencyLayout = new javax.swing.GroupLayout(paneContingency);
        paneContingency.setLayout(paneContingencyLayout);
        paneContingencyLayout.setHorizontalGroup(
            paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContingencyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(paneContingencyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        paneContingencyLayout.setVerticalGroup(
            paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneContingencyLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(scrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        lpaneReports.add(paneContingency, "card2");

        paneUserContingencies.setBackground(new java.awt.Color(204, 255, 204));

        jTextField6.setText("jTextField5");

        jLabel9.setText("Total Financial Loss To Date:");

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        scrollPane5.add(jScrollPane8);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        scrollPane5.add(jScrollPane9);

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        scrollPane5.add(jScrollPane10);

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(jTable11);

        scrollPane5.add(jScrollPane11);

        javax.swing.GroupLayout paneUserContingenciesLayout = new javax.swing.GroupLayout(paneUserContingencies);
        paneUserContingencies.setLayout(paneUserContingenciesLayout);
        paneUserContingenciesLayout.setHorizontalGroup(
            paneUserContingenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUserContingenciesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(paneUserContingenciesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        paneUserContingenciesLayout.setVerticalGroup(
            paneUserContingenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUserContingenciesLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(scrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(paneUserContingenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        lpaneReports.add(paneUserContingencies, "card3");

        paneBuildingInventory.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout paneBuildingInventoryLayout = new javax.swing.GroupLayout(paneBuildingInventory);
        paneBuildingInventory.setLayout(paneBuildingInventoryLayout);
        paneBuildingInventoryLayout.setHorizontalGroup(
            paneBuildingInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        paneBuildingInventoryLayout.setVerticalGroup(
            paneBuildingInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        lpaneReports.add(paneBuildingInventory, "card4");

        btnContingency.setText("Contingency");
        btnContingency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContingencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panReportsLayout = new javax.swing.GroupLayout(panReports);
        panReports.setLayout(panReportsLayout);
        panReportsLayout.setHorizontalGroup(
            panReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnContingency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserContingency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuildingInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lpaneReports, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panReportsLayout.setVerticalGroup(
            panReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportsLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnContingency)
                .addGap(32, 32, 32)
                .addComponent(btnUserContingency)
                .addGap(33, 33, 33)
                .addComponent(btnBuildingInventory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpaneReports)
                .addContainerGap())
        );

        tabDashboard.addTab("Reports", panReports);

        javax.swing.GroupLayout panProfileLayout = new javax.swing.GroupLayout(panProfile);
        panProfile.setLayout(panProfileLayout);
        panProfileLayout.setHorizontalGroup(
            panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panProfileLayout.setVerticalGroup(
            panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabDashboard.addTab("Profile", panProfile);

        javax.swing.GroupLayout panUsersLayout = new javax.swing.GroupLayout(panUsers);
        panUsers.setLayout(panUsersLayout);
        panUsersLayout.setHorizontalGroup(
            panUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panUsersLayout.setVerticalGroup(
            panUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabDashboard.addTab("Users", panUsers);

        jLayeredPane1.add(tabDashboard, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        switchPanels(paneCheckOut,1);
        //sets the table model for the jtable and adds in the column titles
        DefaultTableModel tblModel = new DefaultTableModel();
        jTable2.setModel(tblModel);
        String[] colTitles = {"Equipment Id", "Equipment Name", "Price", "Status", "Building Id", "Date Added"};
        tblModel.setColumnIdentifiers(colTitles);
        
        ecsDB db = new ecsDB();
        //populate jtable
        try {
            ArrayList<Equipment> list = db.getEquipment();
            for (int i = 0; i < list.size(); i++)
            {
                Equipment equipment = list.get(i);
                
                Object[] row = {equipment.getId(), equipment.getName(), equipment.getPrice(), equipment.getStatus(),
                    equipment.getBuildingId(), equipment.getDateAdded()};
                
                tblModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        switchPanels(paneCheckIn,1);
        //sets the table model for the jtable and adds in the column titles
        DefaultTableModel tblModel = new DefaultTableModel();
        jTable1.setModel(tblModel);
        String[] colTitles = {"Equipment Id", "Equipment Name", "Price", "Status", "Building Id", "Date Added"};
        tblModel.setColumnIdentifiers(colTitles);
        
        ecsDB db = new ecsDB();
        //populate jtable
        try {
            ArrayList<Equipment> list = db.getEquipment();
            for (int i = 0; i < list.size(); i++)
            {
                Equipment equipment = list.get(i);
                
                Object[] row = {equipment.getId(), equipment.getName(), equipment.getPrice(), equipment.getStatus(),
                    equipment.getBuildingId(), equipment.getDateAdded()};
                
                tblModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnUserContingencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserContingencyActionPerformed
        // TODO add your handling code here:
        switchPanels(paneUserContingencies,2);
        
    }//GEN-LAST:event_btnUserContingencyActionPerformed

    private void btnContingencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContingencyActionPerformed
        // TODO add your handling code here:
        switchPanels(paneContingency,2);
        
    }//GEN-LAST:event_btnContingencyActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        switchPanels(paneEdit,1);
        //sets the table model for the jtable and adds in the column titles
        DefaultTableModel tblModel = new DefaultTableModel();
        jTable3.setModel(tblModel);
        String[] colTitles = {"Equipment Id", "Equipment Name", "Price", "Status", "Building Id", "Date Added"};
        tblModel.setColumnIdentifiers(colTitles);
        
        ecsDB db = new ecsDB();
        //populate jtable
        try {
            ArrayList<Equipment> list = db.getEquipment();
            for (int i = 0; i < list.size(); i++)
            {
                Equipment equipment = list.get(i);
                
                Object[] row = {equipment.getId(), equipment.getName(), equipment.getPrice(), equipment.getStatus(),
                    equipment.getBuildingId(), equipment.getDateAdded()};
                
                tblModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }        

    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
            jLayeredPane1.removeAll();
            jLayeredPane1.add(tabDashboard);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
            jLayeredPane1.removeAll();
            jLayeredPane1.add(paneLogin);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCheckout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckout2ActionPerformed
        // Select a tool to check out from jtable2 and check it out
        // the columns are used to grab the correct column of data at a selected row
        int column = 0;
        int column1 = 1;
        int column3 = 2;
        int column2 = 3;
        int column4 = 4;
        int column5 = 5;
          //user selected row of jtable
        int row = jTable2.getSelectedRow();
        //equipment Id
        String value = jTable2.getModel().getValueAt(row, column).toString();
        //status
        String value2 = jTable2.getModel().getValueAt(row, column2).toString();
         //convert string value to int
        int equipmentId = Integer.parseInt(value);
        //Checks out the tool, changes avilable to out
        if(value2.equals("Avilable"))
        {
            value2 = "Out";
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Not Avilable for check out");
        }
        //grabs the rest of the equipment class info
        String equipmentName = jTable2.getModel().getValueAt(row, column1).toString();
        String equipmentPrice = jTable2.getModel().getValueAt(row, column3).toString();
        double equipPrice = Double.parseDouble(equipmentPrice);
        String equipmentBuilding = jTable2.getModel().getValueAt(row, column4).toString();
        int equipBuilding = Integer.parseInt(equipmentBuilding);
        String equipmentDate = jTable2.getModel().getValueAt(row, column5).toString();
        //create equipment type to save
        Equipment equipment;
        equipment = new Equipment(equipmentId, equipmentName, equipPrice, value2, equipBuilding, equipmentDate);
        //open database
        ecsDB db = new ecsDB();
        //save changes
        try{
         db.equipmentCheckOut(equipment);
         JOptionPane.showMessageDialog(this, "Contact was written to the database");
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckout2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Check in the tool if not broken, lost, or stolen
        // the columns are used to grab the correct column of data at a selected row
        int column = 0;
        int column1 = 1;
        int column3 = 2;
        int column2 = 3;
        int column4 = 4;
        int column5 = 5;
        //user selected row of jtable
        int row = jTable1.getSelectedRow();
        //equipment Id
        String value = jTable1.getModel().getValueAt(row, column).toString();
        //status
        String value2 = jTable1.getModel().getValueAt(row, column2).toString();
        //convert string value to int
        int equipmentId = Integer.parseInt(value);
        //Checks in the tool, changes out to avilable
        if(value2.equals("Out"))
        {
            value2 = "Avilable";
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Not Avilable for check in");
        }
        //grabs the rest of the equipment class info
        String equipmentName = jTable1.getModel().getValueAt(row, column1).toString();
        String equipmentPrice = jTable1.getModel().getValueAt(row, column3).toString();
        double equipPrice = Double.parseDouble(equipmentPrice);
        String equipmentBuilding = jTable1.getModel().getValueAt(row, column4).toString();
        int equipBuilding = Integer.parseInt(equipmentBuilding);
        String equipmentDate = jTable1.getModel().getValueAt(row, column5).toString();
        Equipment equipment;
        //create equipment type to save
        equipment = new Equipment(equipmentId, equipmentName, equipPrice, value2, equipBuilding, equipmentDate);
        //open database
        ecsDB db = new ecsDB();
        //save changes
        try{
         db.equipmentCheckOut(equipment);
         JOptionPane.showMessageDialog(this, "Contact was written to the database");
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBrokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrokenActionPerformed
        // reports item as Broken
        int column = 0;
        int column1 = 1;
        int column3 = 2;
        int column2 = 3;
        int column4 = 4;
        int column5 = 5;
        //user selected row of jtable
        int row = jTable1.getSelectedRow();
        //equipment Id
        String value = jTable1.getModel().getValueAt(row, column).toString();
        //status
        String value2 = jTable1.getModel().getValueAt(row, column2).toString();
        //convert string value to int
        int equipmentId = Integer.parseInt(value);
        //Checks in the tool, changes out to avilable
        if(value2.equals("Out"))
        {
            value2 = "Broken";
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Tool needs to be checked out in order to report broken.");
        }
        //grabs the rest of the equipment class info
        String equipmentName = jTable1.getModel().getValueAt(row, column1).toString();
        String equipmentPrice = jTable1.getModel().getValueAt(row, column3).toString();
        double equipPrice = Double.parseDouble(equipmentPrice);
        String equipmentBuilding = jTable1.getModel().getValueAt(row, column4).toString();
        int equipBuilding = Integer.parseInt(equipmentBuilding);
        String equipmentDate = jTable1.getModel().getValueAt(row, column5).toString();
        Equipment equipment;
        //create equipment type to save
        equipment = new Equipment(equipmentId, equipmentName, equipPrice, value2, equipBuilding, equipmentDate);
        //open database
        ecsDB db = new ecsDB();
        //save changes
        try{
         db.equipmentCheckOut(equipment);
         JOptionPane.showMessageDialog(this, "Contact was written to the database");
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBrokenActionPerformed

    private void btnStolenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStolenActionPerformed
        // reports item as stolen
        int column = 0;
        int column1 = 1;
        int column3 = 2;
        int column2 = 3;
        int column4 = 4;
        int column5 = 5;
        //user selected row of jtable
        int row = jTable1.getSelectedRow();
        //equipment Id
        String value = jTable1.getModel().getValueAt(row, column).toString();
        //status
        String value2 = jTable1.getModel().getValueAt(row, column2).toString();
        //convert string value to int
        int equipmentId = Integer.parseInt(value);
        //Checks in the tool, changes out to avilable
        if(value2.equals("Out"))
        {
            value2 = "Stolen";
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Tool needs to be checked out in order to report stolen.");
        }
        //grabs the rest of the equipment class info
        String equipmentName = jTable1.getModel().getValueAt(row, column1).toString();
        String equipmentPrice = jTable1.getModel().getValueAt(row, column3).toString();
        double equipPrice = Double.parseDouble(equipmentPrice);
        String equipmentBuilding = jTable1.getModel().getValueAt(row, column4).toString();
        int equipBuilding = Integer.parseInt(equipmentBuilding);
        String equipmentDate = jTable1.getModel().getValueAt(row, column5).toString();
        Equipment equipment;
        //create equipment type to save
        equipment = new Equipment(equipmentId, equipmentName, equipPrice, value2, equipBuilding, equipmentDate);
        //open database
        ecsDB db = new ecsDB();
        //save changes
        try{
         db.equipmentCheckOut(equipment);
         JOptionPane.showMessageDialog(this, "Contact was written to the database");
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStolenActionPerformed

    private void btnLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLostActionPerformed
        // reports item as lost
        int column = 0;
        int column1 = 1;
        int column3 = 2;
        int column2 = 3;
        int column4 = 4;
        int column5 = 5;
        //user selected row of jtable
        int row = jTable1.getSelectedRow();
        //equipment Id
        String value = jTable1.getModel().getValueAt(row, column).toString();
        //status
        String value2 = jTable1.getModel().getValueAt(row, column2).toString();
        //convert string value to int
        int equipmentId = Integer.parseInt(value);
        //Checks in the tool, changes out to avilable
        if(value2.equals("Out"))
        {
            value2 = "Broken";
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Tool needs to be checked out in order to report lost.");
        }
        //grabs the rest of the equipment class info
        String equipmentName = jTable1.getModel().getValueAt(row, column1).toString();
        String equipmentPrice = jTable1.getModel().getValueAt(row, column3).toString();
        double equipPrice = Double.parseDouble(equipmentPrice);
        String equipmentBuilding = jTable1.getModel().getValueAt(row, column4).toString();
        int equipBuilding = Integer.parseInt(equipmentBuilding);
        String equipmentDate = jTable1.getModel().getValueAt(row, column5).toString();
        Equipment equipment;
        //create equipment type to save
        equipment = new Equipment(equipmentId, equipmentName, equipPrice, value2, equipBuilding, equipmentDate);
        //open database
        ecsDB db = new ecsDB();
        //save changes
        try{
         db.equipmentCheckOut(equipment);
         JOptionPane.showMessageDialog(this, "Contact was written to the database");
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLostActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // adds a new item to inventory (saves it to the database)
        //create default equipment to populate, and placeholders for data from user
        Equipment equipment;
        int id, bId;
        String name, status, date;
        Double price;
        //grab the user entered data and save it to place holders
        id = Integer.parseInt(jtfEquipmentId.getText());
        bId = Integer.parseInt(jtfBuilding.getText());
        name = jtfEquipmentId.getText();
        //they are adding a tool so auto set to avilable
        status = "Avilable";
        date = jtfDate.getText();
        price = Double.parseDouble(jtfPrice.getText());
        //save user info into new equipment type
        equipment = new Equipment(id,name,price,status,bId,date);
        //open database
        ecsDB db = new ecsDB();
        //save changes
        try{
         db.add(equipment);
         JOptionPane.showMessageDialog(this, "Contact was written to the database");
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "JDBC driver not found", "Driver Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ECS().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBroken;
    private javax.swing.JButton btnBuildingInventory;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnCheckout2;
    private javax.swing.JButton btnContingency;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLost;
    private javax.swing.JButton btnStolen;
    private javax.swing.JButton btnUserContingency;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jtfBuilding;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfEquipmentId;
    private javax.swing.JTextField jtfName1;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JLayeredPane lpaneEquipment;
    private javax.swing.JLayeredPane lpaneReports;
    private javax.swing.JPanel panEquipment;
    private javax.swing.JPanel panProfile;
    private javax.swing.JPanel panReports;
    private javax.swing.JPanel panUsers;
    private javax.swing.JPanel paneBuildingInventory;
    private javax.swing.JPanel paneCheckIn;
    private javax.swing.JPanel paneCheckOut;
    private javax.swing.JPanel paneContingency;
    private javax.swing.JPanel paneEdit;
    private javax.swing.JPanel paneLogin;
    private javax.swing.JPanel paneUserContingencies;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane3;
    private java.awt.ScrollPane scrollPane4;
    private java.awt.ScrollPane scrollPane5;
    private javax.swing.JTabbedPane tabDashboard;
    // End of variables declaration//GEN-END:variables
    public void switchPanels(JPanel panel, int x){
        if(x==1){
            lpaneEquipment.removeAll();
            lpaneEquipment.add(panel);
            lpaneEquipment.repaint();
            lpaneEquipment.revalidate();
        }        
        if(x==2){
            lpaneReports.removeAll();
            lpaneReports.add(panel);
            lpaneReports.repaint();
            lpaneReports.revalidate();
        }

    }
}
