
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nick&Tori
 */
public class ECS extends javax.swing.JFrame {

    /**
     * Creates new form ECS
     */
    int userPosition=0;

    public ECS() {
        initComponents();        
        getReports(false,"");
        getBuildingReoprt("1");
        jMenuBar1.hide();
        inptUsername.setText("user2");
        inptPassword.setText("user2");

        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        paneLogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inptUsername = new javax.swing.JTextField();
        inptPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        tabDashboard = new javax.swing.JTabbedPane();
        panEquipment = new javax.swing.JPanel();
        btnCheckOut = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnEditInventory = new javax.swing.JButton();
        lpaneEquipment = new javax.swing.JLayeredPane();
        paneCheckOut = new javax.swing.JPanel();
        scrollPane3 = new java.awt.ScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        paneCheckIn = new javax.swing.JPanel();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        paneEditInventory = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        panReports = new javax.swing.JPanel();
        btnBuildingInventory = new javax.swing.JButton();
        lpaneReports = new javax.swing.JLayeredPane();
        paneContingency = new javax.swing.JPanel();
        inptFinancialLoss = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        scrollPane6 = new java.awt.ScrollPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblContingency = new javax.swing.JTable();
        inptFilterReport = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inptTotalContingencies = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        paneBuildingInventory = new javax.swing.JPanel();
        btnMainBuilding = new java.awt.Button();
        scrollPane5 = new java.awt.ScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBuildingInventory = new javax.swing.JTable();
        btnPrintBuildingRep = new java.awt.Button();
        btnSubBuilding = new java.awt.Button();
        btnContingency = new javax.swing.JButton();
        panProfile = new javax.swing.JPanel();
        panUsers = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 24))); // NOI18N

        inptUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inptPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Password");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Username");

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setText("LOG IN");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inptPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(inptUsername))
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inptUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inptPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnLogin)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneLoginLayout = new javax.swing.GroupLayout(paneLogin);
        paneLogin.setLayout(paneLoginLayout);
        paneLoginLayout.setHorizontalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLoginLayout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        paneLoginLayout.setVerticalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneLoginLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jLayeredPane1.add(paneLogin, "card3");

        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnEditInventory.setLabel("Edit Inventory");
        btnEditInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInventoryActionPerformed(evt);
            }
        });

        lpaneEquipment.setLayout(new java.awt.CardLayout());

        paneCheckOut.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        scrollPane3.add(jScrollPane3);

        jLabel3.setText("CHECK OUT - EQUIPMENT");

        jButton6.setText("Check Out");

        javax.swing.GroupLayout paneCheckOutLayout = new javax.swing.GroupLayout(paneCheckOut);
        paneCheckOut.setLayout(paneCheckOutLayout);
        paneCheckOutLayout.setHorizontalGroup(
            paneCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckOutLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(paneCheckOutLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(paneCheckOutLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneCheckOutLayout.setVerticalGroup(
            paneCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckOutLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton6)
                .addGap(50, 50, 50))
        );

        lpaneEquipment.add(paneCheckOut, "card3");

        paneCheckIn.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        scrollPane2.add(jScrollPane1);

        jLabel2.setText("CHECK IN - USER HISTORY");

        jButton2.setText("Check In");

        jButton3.setText("stolen");

        jButton4.setText("Broken");

        jButton5.setText("Lost");

        javax.swing.GroupLayout paneCheckInLayout = new javax.swing.GroupLayout(paneCheckIn);
        paneCheckIn.setLayout(paneCheckInLayout);
        paneCheckInLayout.setHorizontalGroup(
            paneCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckInLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(paneCheckInLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneCheckInLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneCheckInLayout.setVerticalGroup(
            paneCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCheckInLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(paneCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(56, 56, 56))
        );

        lpaneEquipment.add(paneCheckIn, "card3");

        paneEditInventory.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        scrollPane1.add(jScrollPane2);

        jButton1.setText("Delete");

        jLabel1.setText("Name");

        jTextField1.setText("jTextField1");

        jLabel4.setText("Price");

        jTextField2.setText("jTextField1");

        jLabel5.setText("Quantity");

        jTextField3.setText("jTextField1");

        jLabel6.setText("Building");

        jTextField4.setText("jTextField1");

        jButton7.setText("ADD");

        jLabel7.setText("EDIT INVENTORY");

        javax.swing.GroupLayout paneEditInventoryLayout = new javax.swing.GroupLayout(paneEditInventory);
        paneEditInventory.setLayout(paneEditInventoryLayout);
        paneEditInventoryLayout.setHorizontalGroup(
            paneEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditInventoryLayout.createSequentialGroup()
                .addGroup(paneEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditInventoryLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(paneEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneEditInventoryLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(paneEditInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneEditInventoryLayout.setVerticalGroup(
            paneEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEditInventoryLayout.createSequentialGroup()
                .addGroup(paneEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneEditInventoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addGroup(paneEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneEditInventoryLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jButton1))
                    .addGroup(paneEditInventoryLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton7)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        lpaneEquipment.add(paneEditInventory, "card4");

        javax.swing.GroupLayout panEquipmentLayout = new javax.swing.GroupLayout(panEquipment);
        panEquipment.setLayout(panEquipmentLayout);
        panEquipmentLayout.setHorizontalGroup(
            panEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEquipmentLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lpaneEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panEquipmentLayout.setVerticalGroup(
            panEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEquipmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpaneEquipment)
                .addContainerGap())
            .addGroup(panEquipmentLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnCheckOut)
                .addGap(32, 32, 32)
                .addComponent(btnCheckIn)
                .addGap(33, 33, 33)
                .addComponent(btnEditInventory)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabDashboard.addTab("Equipment", panEquipment);

        btnBuildingInventory.setText("Building Inventory");
        btnBuildingInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildingInventoryActionPerformed(evt);
            }
        });

        lpaneReports.setLayout(new java.awt.CardLayout());

        inptFinancialLoss.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Total Financial Loss To Date:");

        tblContingency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(tblContingency);

        scrollPane6.add(jScrollPane12);

        inptFilterReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inptFilterReportKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Filter (Name or User ID):");

        inptTotalContingencies.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total Contingencies");

        javax.swing.GroupLayout paneContingencyLayout = new javax.swing.GroupLayout(paneContingency);
        paneContingency.setLayout(paneContingencyLayout);
        paneContingencyLayout.setHorizontalGroup(
            paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(paneContingencyLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inptFinancialLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inptTotalContingencies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(paneContingencyLayout.createSequentialGroup()
                .addGroup(paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneContingencyLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(scrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneContingencyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inptFilterReport, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneContingencyLayout.setVerticalGroup(
            paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneContingencyLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inptFilterReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(paneContingencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inptFinancialLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inptTotalContingencies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35))
        );

        lpaneReports.add(paneContingency, "card2");

        paneBuildingInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnMainBuilding.setLabel("Main Building");
        btnMainBuilding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainBuildingActionPerformed(evt);
            }
        });

        tblBuildingInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblBuildingInventory);

        scrollPane5.add(jScrollPane5);

        btnPrintBuildingRep.setActionCommand("print");
        btnPrintBuildingRep.setLabel("Print");
        btnPrintBuildingRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBuildingRepActionPerformed(evt);
            }
        });

        btnSubBuilding.setLabel("Sub Building");
        btnSubBuilding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubBuildingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBuildingInventoryLayout = new javax.swing.GroupLayout(paneBuildingInventory);
        paneBuildingInventory.setLayout(paneBuildingInventoryLayout);
        paneBuildingInventoryLayout.setHorizontalGroup(
            paneBuildingInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuildingInventoryLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnMainBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSubBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(btnPrintBuildingRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(paneBuildingInventoryLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(scrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneBuildingInventoryLayout.setVerticalGroup(
            paneBuildingInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBuildingInventoryLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(scrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBuildingInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMainBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrintBuildingRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        btnPrintBuildingRep.getAccessibleContext().setAccessibleName("print");

        lpaneReports.add(paneBuildingInventory, "card4");

        btnContingency.setText("Contingency");
        btnContingency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContingencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panReportsLayout = new javax.swing.GroupLayout(panReports);
        panReports.setLayout(panReportsLayout);
        panReportsLayout.setHorizontalGroup(
            panReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnContingency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuildingInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(lpaneReports, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panReportsLayout.setVerticalGroup(
            panReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panReportsLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnContingency)
                .addGap(18, 18, 18)
                .addComponent(btnBuildingInventory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpaneReports)
                .addContainerGap())
        );

        tabDashboard.addTab("Reports", panReports);

        javax.swing.GroupLayout panProfileLayout = new javax.swing.GroupLayout(panProfile);
        panProfile.setLayout(panProfileLayout);
        panProfileLayout.setHorizontalGroup(
            panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panProfileLayout.setVerticalGroup(
            panProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabDashboard.addTab("Profile", panProfile);

        javax.swing.GroupLayout panUsersLayout = new javax.swing.GroupLayout(panUsers);
        panUsers.setLayout(panUsersLayout);
        panUsersLayout.setHorizontalGroup(
            panUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panUsersLayout.setVerticalGroup(
            panUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tabDashboard.addTab("Users", panUsers);

        jLayeredPane1.add(tabDashboard, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        switchPanels(paneCheckOut,1);
        

        
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        switchPanels(paneCheckIn,1);

    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnContingencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContingencyActionPerformed
        // TODO add your handling code here:
        switchPanels(paneContingency,2);
   
        
    }//GEN-LAST:event_btnContingencyActionPerformed

    private void btnEditInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInventoryActionPerformed
        // TODO add your handling code here:
                switchPanels(paneEditInventory,1);

    }//GEN-LAST:event_btnEditInventoryActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        int validUser=validateUser(inptUsername.getText(),inptPassword.getText());
        if(validUser==1){
        
            jLayeredPane1.removeAll();
            jLayeredPane1.add(tabDashboard);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
            jMenuBar1.show();
        if(userPosition!=1){
        hideNonAdmin();
        }
        }
        else{    JOptionPane.showMessageDialog(null, "Incorrect Username or Password",
      "Access Denied", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jMenuBar1.hide();

            jLayeredPane1.removeAll();
            jLayeredPane1.add(paneLogin);
            jLayeredPane1.repaint();
            jLayeredPane1.revalidate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnBuildingInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildingInventoryActionPerformed
        // TODO add your handling code here:
        switchPanels(paneBuildingInventory,2);

    }//GEN-LAST:event_btnBuildingInventoryActionPerformed

    private void btnMainBuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainBuildingActionPerformed
        // TODO add your handling code here:
       getBuildingReoprt("1");
    }//GEN-LAST:event_btnMainBuildingActionPerformed

    private void btnPrintBuildingRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBuildingRepActionPerformed
        // TODO add your handling code here:
        try {
            boolean print = tblBuildingInventory.print();
            if (!print) {
               // JOptionPane.showMessageDialog(null, "Unable To Print !!..");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnPrintBuildingRepActionPerformed

    private void btnSubBuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubBuildingActionPerformed
        // TODO add your handling code here:
               getBuildingReoprt("2");

    }//GEN-LAST:event_btnSubBuildingActionPerformed

    private void inptFilterReportKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inptFilterReportKeyReleased
        // TODO add your handling code here:
                       getReports( true, inptFilterReport.getText());
                       System.out.print(inptFilterReport.getText());
    }//GEN-LAST:event_inptFilterReportKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ECS().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuildingInventory;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnContingency;
    private javax.swing.JButton btnEditInventory;
    private javax.swing.JButton btnLogin;
    private java.awt.Button btnMainBuilding;
    private java.awt.Button btnPrintBuildingRep;
    private java.awt.Button btnSubBuilding;
    private javax.swing.JTextField inptFilterReport;
    private javax.swing.JTextField inptFinancialLoss;
    private javax.swing.JTextField inptPassword;
    private javax.swing.JTextField inptTotalContingencies;
    private javax.swing.JTextField inptUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLayeredPane lpaneEquipment;
    private javax.swing.JLayeredPane lpaneReports;
    private javax.swing.JPanel panEquipment;
    private javax.swing.JPanel panProfile;
    private javax.swing.JPanel panReports;
    private javax.swing.JPanel panUsers;
    private javax.swing.JPanel paneBuildingInventory;
    private javax.swing.JPanel paneCheckIn;
    private javax.swing.JPanel paneCheckOut;
    private javax.swing.JPanel paneContingency;
    private javax.swing.JPanel paneEditInventory;
    private javax.swing.JPanel paneLogin;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane3;
    private java.awt.ScrollPane scrollPane5;
    private java.awt.ScrollPane scrollPane6;
    private javax.swing.JTabbedPane tabDashboard;
    private javax.swing.JTable tblBuildingInventory;
    private javax.swing.JTable tblContingency;
    // End of variables declaration//GEN-END:variables
    public void switchPanels(JPanel panel, int x){
        if(x==1){
            lpaneEquipment.removeAll();
            lpaneEquipment.add(panel);
            lpaneEquipment.repaint();
            lpaneEquipment.revalidate();
        }        
        if(x==2){
            lpaneReports.removeAll();
            lpaneReports.add(panel);
            lpaneReports.repaint();
            lpaneReports.revalidate();
        }

    }
    
  public void getReports(boolean filter, String filterString ){
//contengency report
DefaultTableModel reportTableModel = new DefaultTableModel();
        tblContingency.setModel(reportTableModel);
        double totalContingency=0;

        String[] colTitles = {"Transaction ID", "Transaction Type", "Equipment", "Price", "Employee",  "Employee ID"};
        reportTableModel.setColumnIdentifiers(colTitles);
        
        ecsDB db2 = new ecsDB();
        try {

             ArrayList<Reports> records =null;
            if(filter==true )
            {
                records = db2.getContingencyRec(true,filterString);

            }
            else{                      
                records = db2.getContingencyRec(false,filterString);
            }

            for (int i = 0; i < records.size(); i++) {
                Reports odr = records.get(i);  
                
                Object[] row = {odr.getTransactionID(), odr.getTransactionType(), odr.getEquipmentName(), odr.getPrice(), odr.getName().toUpperCase(), odr.getUserID()};
                reportTableModel.addRow(row);
                totalContingency+=odr.getPrice();
                                         inptTotalContingencies.setText(String.valueOf(i+1));

                 
                 
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error DB driver not found", "Driver Not Found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "DB ERROR: " + ex.getMessage(), "DB ERROR", JOptionPane.ERROR_MESSAGE);
        }
        System.out.println(totalContingency+"<--");
                         inptFinancialLoss.setText(String.valueOf(totalContingency));

}
//user contengency report
//  public void getUserContingency(){
//  DefaultTableModel userContingencyModel = new DefaultTableModel();
//        tblUserContingency.setModel(userContingencyModel);
//
//        String[] colTitles = {"Employee", "Employee ID", "Equipment incidents",};
//        userContingencyModel.setColumnIdentifiers(colTitles);
//        
//        ecsDB db2 = new ecsDB();
//        try {
//            ArrayList<Reports> records = db2.getUserContingencyRec();
//            for (int i = 0; i < records.size(); i++) {
//                Reports odr = records.get(i);    
//                Object[] row = {odr.getName().toUpperCase(), odr.getUserID(), odr.getCntingency()};
//                //reportTableModel.addRow(row);
//                 userContingencyModel.addRow(row);
//            }
//        } catch (ClassNotFoundException ex) {
//            JOptionPane.showMessageDialog(this, "Error DB driver not found", "Driver Not Found", JOptionPane.ERROR_MESSAGE);
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "DB ERROR: " + ex.getMessage(), "DB ERROR", JOptionPane.ERROR_MESSAGE);
//        }
//        
//}
  
//user contengency report
  public void getBuildingReoprt(String x){
  DefaultTableModel userContingencyModel = new DefaultTableModel();
        tblBuildingInventory.setModel(userContingencyModel);

        String[] colTitles = {"Equipment Id", "Equipment Name", "Building"};
        userContingencyModel.setColumnIdentifiers(colTitles);
        
        ecsDB db2 = new ecsDB();
        try {
            ArrayList<Reports> records = db2.getBuildingReport(x);
            for (int i = 0; i < records.size(); i++) {
                Reports odr = records.get(i);      

                Object[] row = {odr.getEquipmentId(), odr.getEquipmentName(), odr.getBuildingName()};
                //reportTableModel.addRow(row);
                //System.out.println(Arrays.toString(row));

                 userContingencyModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error DB driver not found", "Driver Not Found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "DB ERROR: " + ex.getMessage(), "DB ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
}
  


  public int validateUser(String un, String pw){
int validUser=0;
        
          ecsDB db2 = new ecsDB();
        try {
            ArrayList<User> records = db2.validateUser(un , pw);
            if(records.size()>0){validUser=1;}
           
               
            for (int i = 0; i < records.size(); i++) {
                User odr = records.get(i);      
                Object[] row = {odr.getUserName(), odr.getPassword(), odr.getPosition()};
                //reportTableModel.addRow(row);
                System.out.println(Arrays.toString(row));
                userPosition=odr.getPosition();
             

               //  userContingencyModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error DB driver not found", "Driver Not Found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "DB ERROR: " + ex.getMessage(), "DB ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return validUser;
}
private void hideNonAdmin(){
paneEditInventory.hide();
btnEditInventory.hide();
jMenuBar1.show();
}

}
